node build/index.js /Users/santhosbaala/Downloads/lichess-games/2013-01.pgn ~/Downloads/lichess-games/out/2013-01.tsv blitz
node build/index.js /Users/santhosbaala/Downloads/lichess-games/2013-02.pgn ~/Downloads/lichess-games/out/2013-02.tsv blitz
node build/index.js /Users/santhosbaala/Downloads/lichess-games/2013-03.pgn ~/Downloads/lichess-games/out/2013-03.tsv blitz
node build/index.js /Users/santhosbaala/Downloads/lichess-games/2013-04.pgn ~/Downloads/lichess-games/out/2013-04.tsv blitz
node build/index.js /Users/santhosbaala/Downloads/lichess-games/2013-05.pgn ~/Downloads/lichess-games/out/2013-05.tsv blitz
node build/index.js /Users/santhosbaala/Downloads/lichess-games/2013-06.pgn ~/Downloads/lichess-games/out/2013-06.tsv blitz
node build/index.js /Users/santhosbaala/Downloads/lichess-games/2013-07.pgn ~/Downloads/lichess-games/out/2013-07.tsv blitz
node build/index.js /Users/santhosbaala/Downloads/lichess-games/2013-08.pgn ~/Downloads/lichess-games/out/2013-08.tsv blitz
node build/index.js /Users/santhosbaala/Downloads/lichess-games/2013-09.pgn ~/Downloads/lichess-games/out/2013-09.tsv blitz
node build/index.js /Users/santhosbaala/Downloads/lichess-games/2013-10.pgn ~/Downloads/lichess-games/out/2013-10.tsv blitz
node build/index.js /Users/santhosbaala/Downloads/lichess-games/2013-11.pgn ~/Downloads/lichess-games/out/2013-11.tsv blitz
node build/index.js /Users/santhosbaala/Downloads/lichess-games/2013-12.pgn ~/Downloads/lichess-games/out/2013-12.tsv blitz
node build/index.js /Users/santhosbaala/Downloads/lichess-games/2014-01.pgn ~/Downloads/lichess-games/out/2014-01.tsv blitz
